# Generated by Django 3.2.8 on 2021-10-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='name')),
                ('price', models.CharField(max_length=20, verbose_name='price')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='desc')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('price', models.CharField(max_length=20, verbose_name='price')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='img')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='desc')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='order.Product', verbose_name='products'),
        ),
    ]
